export const TOOLS = Object.freeze([
  { id: "curl", name: "curl" },
  { id: "wget", name: "wget" },
  { id: "whatweb", name: "whatweb" },
  { id: "nikto", name: "nikto" },
  { id: "ffuf", name: "ffuf" },
  { id: "gobuster", name: "gobuster" },
  { id: "feroxbuster", name: "feroxbuster" },
  { id: "dirsearch", name: "dirsearch" },
  { id: "wfuzz", name: "wfuzz" },
  { id: "wpscan", name: "wpscan" },
  { id: "sqlmap", name: "sqlmap" },
  { id: "burp-suite", name: "burp-suite" },
  { id: "owasp-zap", name: "owasp-zap" },
]);
