function freezeSources(sources) {
  return Object.freeze(
    sources.map((source) => Object.freeze({
      ...source,
      topics: Object.freeze([...source.topics]),
    })),
  );
}

export const ML_SOURCES = freezeSources([
  {
    id: "ultralytics-docs",
    title: "Ultralytics YOLO documentation",
    owner: "Ultralytics",
    url: "https://docs.ultralytics.com/",
    sourceType: "official-documentation",
    licenseStatus: "official-software-and-documentation",
    licenseName: "AGPL-3.0 or Enterprise for Ultralytics software",
    versionOrDate: "YOLO26 current family with YOLO11 and YOLOv8 compatibility",
    topics: ["object detection", "open-vocabulary detection", "instance segmentation", "semantic segmentation", "monocular depth", "training", "validation", "inference", "export"],
    verifiedAt: "2026-08-18",
  },
  {
    id: "pytorch-docs",
    title: "PyTorch documentation",
    owner: "PyTorch Foundation",
    url: "https://docs.pytorch.org/docs/stable/",
    sourceType: "official-documentation",
    licenseStatus: "official-open-source-documentation",
    licenseName: "BSD-style PyTorch software license; documentation terms apply",
    versionOrDate: "Stable documentation",
    topics: ["training", "datasets", "data loaders", "LSTM", "TorchScript", "ONNX"],
    verifiedAt: "2026-07-27",
  },
  {
    id: "tensorflow-docs",
    title: "TensorFlow API documentation",
    owner: "Google",
    url: "https://www.tensorflow.org/api_docs",
    sourceType: "official-documentation",
    licenseStatus: "official-open-documentation",
    licenseName: "CC BY 4.0 documentation; Apache-2.0 code samples",
    versionOrDate: "TensorFlow 2.x API",
    topics: ["Keras", "transfer learning", "image classification", "TensorFlow Lite", "quantization"],
    verifiedAt: "2026-07-27",
  },
  {
    id: "handson-ml3",
    title: "Hands-On Machine Learning, third-edition notebooks",
    owner: "Aurélien Géron",
    url: "https://github.com/ageron/handson-ml3",
    sourceType: "curriculum-repository",
    licenseStatus: "permissive-reference",
    licenseName: "Apache-2.0",
    versionOrDate: "Third edition",
    topics: ["scikit-learn", "Keras", "TensorFlow", "data preparation", "classical ML", "deep learning"],
    verifiedAt: "2026-07-27",
  },
  {
    id: "pytorch-deep-learning",
    title: "PyTorch Deep Learning",
    owner: "Daniel Bourke",
    url: "https://github.com/mrdbourke/pytorch-deep-learning",
    sourceType: "curriculum-repository",
    licenseStatus: "permissive-reference",
    licenseName: "MIT",
    versionOrDate: "Repository main branch",
    topics: ["PyTorch workflows", "custom datasets", "transfer learning", "experiment tracking", "deployment"],
    verifiedAt: "2026-07-27",
  },
  {
    id: "handson-mlp",
    title: "Hands-On Machine Learning with Scikit-Learn and PyTorch",
    owner: "Aurélien Géron",
    url: "https://github.com/ageron/handson-mlp",
    sourceType: "curriculum-repository",
    licenseStatus: "permissive-reference",
    licenseName: "Apache-2.0",
    versionOrDate: "Repository main branch",
    topics: ["scikit-learn", "PyTorch", "Hugging Face", "transformers", "quantization", "reinforcement learning"],
    verifiedAt: "2026-07-27",
  },
  {
    id: "hands-on-llm",
    title: "Hands-On Large Language Models",
    owner: "Jay Alammar and Maarten Grootendorst",
    url: "https://github.com/HandsOnLLM/Hands-On-Large-Language-Models",
    sourceType: "curriculum-repository",
    licenseStatus: "permissive-reference",
    licenseName: "Apache-2.0",
    versionOrDate: "Repository main branch",
    topics: ["tokens", "embeddings", "semantic search", "RAG", "generation", "multimodal workflows", "fine-tuning"],
    verifiedAt: "2026-07-27",
  },
  {
    id: "unsloth-core",
    title: "Unsloth Core",
    owner: "Unsloth AI",
    url: "https://github.com/unslothai/unsloth",
    sourceType: "framework-repository",
    licenseStatus: "permissive-core-only",
    licenseName: "Apache-2.0 for Core; Studio and CLI are excluded from this source record",
    versionOrDate: "Repository main branch",
    topics: ["local inference", "LoRA", "QLoRA", "fine-tuning", "quantization", "adapter export"],
    verifiedAt: "2026-07-27",
  },
  {
    id: "cs50-ai",
    title: "CS50's Introduction to Artificial Intelligence with Python",
    owner: "Harvard University",
    url: "https://cs50.harvard.edu/ai/",
    sourceType: "course",
    licenseStatus: "link-only-noncommercial-course",
    licenseName: "CC BY-NC-SA 4.0 course materials",
    versionOrDate: "Official course website",
    topics: ["search", "knowledge", "uncertainty", "optimization", "learning", "neural networks", "language"],
    verifiedAt: "2026-07-27",
  },
]);

export function getSourceById(sourceId) {
  return ML_SOURCES.find(({ id }) => id === sourceId) ?? null;
}
