export const TOOLS = Object.freeze([
  { id: "responder", name: "responder" },
  { id: "getnpusers", name: "getnpusers" },
  { id: "getuserspns", name: "getuserspns" },
  { id: "psexec", name: "psexec" },
  { id: "wmiexec", name: "wmiexec" },
  { id: "smbexec", name: "smbexec" },
  { id: "atexec", name: "atexec" },
  { id: "ntlmrelayx", name: "ntlmrelayx" },
  { id: "gettgt", name: "gettgt" },
  { id: "getst", name: "getst" },
  { id: "ticketer", name: "ticketer" },
  { id: "bloodhound-python", name: "bloodhound-python" },
  { id: "sharphound", name: "sharphound" },
  { id: "ldapdomaindump", name: "ldapdomaindump" },
  { id: "mimikatz", name: "mimikatz" },
  { id: "rubeus", name: "rubeus" },
  { id: "powerview", name: "powerview" },
  { id: "certipy", name: "certipy" },
]);
